#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Stable Extension Distribution Pipeline
on:
  pull_request:
    branches:
      - v1.1.2
    paths-ignore:
      - '**/README.md'
      - 'doc/**'
  push:
    branches:
      - v1.1.2
    paths-ignore:
      - '**/README.md'
      - 'doc/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/v1.1.2' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.1.2
    with:
      duckdb_version: v1.1.2
      extension_name: vss
      ci_tools_version: main

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@v1.1.2
    secrets: inherit
    with:
      duckdb_version: v1.1.2
      extension_name: vss
      deploy_latest: ${{ startsWith(github.ref, 'refs/heads/v') || github.ref == 'refs/heads/main' }}
